### ISSUE TITLE
How to reproduce this project

### ISSUE THREAD

**Issue by awesomeNabi** [ALRhub/MaIL#1]
Nice work!I would like to inquire about the process of training a model locally. Could you please provide a comprehensive guide on the necessary preparations?

**Comment by xiaogangjia** [comment]
Hi, thanks a lot for your interest! Sorry for the current state of this repo. I will make a comprehensive Readme this week.

**Comment by awesomeNabi** [comment]
Thanks!Really looking forward to it.
